export const ADD_BURGUER = 'ADD_BURGUER'
export const REMOVE_BURGUER = 'REMOVE_BURGUER'
export const SET_INGREDIENTS = 'SET_INGREDIENTS'
export const FETCH_INGREDIENTS_FAIL = 'FETCH_INGREDIENTS_FAIL'

export const PURCHASE_BURGER_SUCCESS =  'PURCHASE_BURGER_SUCCESS'
export const PURCHASE_BURGER_FAIL = 'PURCHASE_BURGER_FAIL'